# ===============================
# SERVER CONFIG
# ===============================
server.port=8081
spring.application.name=sme-lend-backend

# ===============================
# DATABASE CONFIG (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/sme_lend?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Newpassword123!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# ===============================
# LOGGING
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ===============================
# SWAGGER / OPENAPI
# ===============================
springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/v3/api-docs

# ===============================
# JWT
# ===============================
jwt.secret=smelend-super-secure-secret-key-2026-backend-very-safe
jwt.exp-minutes=120

# ===============================
# SYSTEM USERS BOOTSTRAP
# ===============================
app.bootstrap.admin.full-name=System Admin
app.bootstrap.admin.email=admin@smelend.com
app.bootstrap.admin.password=Admin@123
app.bootstrap.admin.phone=9999999999

app.bootstrap.agent.full-name=Field Agent
app.bootstrap.agent.email=agent1@test.com
app.bootstrap.agent.password=Pass@123
app.bootstrap.agent.phone=9000000001

app.bootstrap.underwriter.full-name=Underwriter User
app.bootstrap.underwriter.email=underwriter1@test.com
app.bootstrap.underwriter.password=Pass@123
app.bootstrap.underwriter.phone=9000000002

app.bootstrap.operations.full-name=Operations User
app.bootstrap.operations.email=operations1@test.com
app.bootstrap.operations.password=Pass@123
app.bootstrap.operations.phone=9000000003

app.bootstrap.servicing.full-name=Servicing User
app.bootstrap.servicing.email=servicing1@test.com
app.bootstrap.servicing.password=Pass@123
app.bootstrap.servicing.phone=9000000004

app.bootstrap.collections.full-name=Collections User
app.bootstrap.collections.email=collections1@test.com
app.bootstrap.collections.password=Pass@123
app.bootstrap.collections.phone=9000000005

app.bootstrap.risk.full-name=Risk User
app.bootstrap.risk.email=risk1@test.com
app.bootstrap.risk.password=Pass@123
app.bootstrap.risk.phone=9000000006

app.bootstrap.compliance.full-name=Compliance User
app.bootstrap.compliance.email=compliance1@test.com
app.bootstrap.compliance.password=Pass@123
app.bootstrap.compliance.phone=9000000007